### ISSUE TITLE
Unable to connect the SARA R510M8S module to the network with Hologram SIM, despite correct APN configuration in Vietnam.

### ISSUE THREAD

**Issue by zumintam** [sparkfun/SparkFun_u-blox_SARA-R5_Arduino_Library#52]
Your workbench
Platform: Development board or microcontroller with SARA R510M8S module.
Device version: SARA R510M8S module.
Firmware version: Ensure you are using the latest firmware version for compatibility.
Wiring: The SARA R510M8S module is connected to the microcontroller via UART or other communication interfaces.
Power: Powered by an appropriate DC source (typically 5V for SARA R5 with V_ext).
Additional details: Hologram SIM is used, and the APN "hologram" is configured correctly, but the device cannot find the network or connect.

**Comment by PaulZC** [comment]
Hi @zumintam ,

According to https://www.hologram.io/coverage/ , the providers for Vietnam are:

![image](https://github.com/user-attachments/assets/b6676dc5-13cc-4892-8bab-9ba55bed3897)

Is your area covered by MobiFone or Vinaphone? Do they provide **LTE-M** coverage in your area?

I hope this helps,
Paul

**Comment by zumintam** [comment]
[SARA-R510M8S-00B-01 Registration Status Not Registered(1).pdf](https://github.com/user-attachments/files/17656135/SARA-R510M8S-00B-01.Registration.Status.Not.Registered.1.pdf)

**Comment by zumintam** [comment]
I noticed that several other people are experiencing the same issue as I am, as seen in this forum, and there has still been no response 
https://community.sparkfun.com/t/sara-r5-registration-status-not-registered/45663/6

**Comment by zumintam** [comment]
Dear Paul,

Thank you for the instructions. I will proceed with the update as you suggested. 
I will let you know if any further issues arise. Thank you for your support!

Best regards,
Tam Vu

**Comment by zumintam** [comment]
After reading this, do you think Vietnam's network infrastructure is sufficient for supporting LTE-M effectively?
[Dear Paul.pdf](https://github.com/user-attachments/files/17674780/Dear.Paul.pdf)

**Comment by PaulZC** [comment]
Hello Tam Vu,

It looks like there are no LTE-M operators in your area.

In my area of the UK, I see only:

![image](https://github.com/user-attachments/assets/d3be57ca-0a3c-4106-b385-a2ab75df6927)

But with the LARA-R6001D and the same SIM, I see:

![image](https://github.com/user-attachments/assets/8fae265d-c0b9-485c-841c-d7d5ee13ce37)

Would you like us to ask u-blox for suggestions?

Best wishes,
Paul

**Comment by zumintam** [comment]
**Subject:** Inquiry About Bulk Pricing for SparkFun GPS-RTK2 Board (ZED-F9P)  

Dear SparkFun Team,  

I hope this email finds you well.  

I am interested in purchasing the **SparkFun GPS-RTK2 Board - ZED-F9P (Qwiic)** (GPS-15136) for a project in Vietnam. The listed price is $249.95, and I was wondering if you could offer a better price.  

Could you also let me know the minimum quantity required to qualify for bulk pricing and the best price you can offer at different quantity tiers? Additionally, I would appreciate information about shipping options and costs to Vietnam.  

Thank you for your support, and I look forward to your response.  

Best regards,  
Tam Vu
vuminhtamndc@gmail.com

**Comment by PaulZC** [comment]
Hello Tam Vu,

I will pass your message to my colleagues. SparkFun is closed for the Thanksgiving holiday - it will take them a few days to reply.

Best wishes,
Paul
